### ISSUE TITLE
Inquiry about Commercial Usage and Open Source Plans

### ISSUE THREAD

**Issue by belief-cyf** [sourcegraph/symf#1]
Hello,

I hope this message finds you well.    I am currently exploring the possibility of using your symf program for a commercial project and wanted to reach out to inquire about its licensing terms.

Could you please clarify if the symf program you have provided is intended for commercial use?    Are there any specific licensing conditions or restrictions that I should be aware of?

Additionally, I am curious about your plans regarding open-sourcing the code.    Do you have any intentions to make the source code available to the community in the future?

Your insights on these matters would greatly assist me in making informed decisions for my project.    I appreciate your time and efforts in developing this program, and I look forward to hearing from you.

Best regards

**Comment by wanzirong** [comment]
I discovered Symf by reading Cody's source code. Cody has a strong contextual understanding, and its local search functionality uses Symf. It's an amazing project.

I look forward to it being open-sourced so that the community can help improve Symf together.
